config/routes.rb
Rails.application.routes.draw do
  resources :foods
  resources :orders
  resource :order_details
  
  #root
  root to: "foods#index", 
    as: "foods_index"

  #FOOD MODEL
  #Show food by params
  get "/:id",
    to: "foods#show",
    as: "foods_show"
  #edit food by params
  get "/:id/edit", 
    to: "foods#edit", 
    as: "foods_edit"
  #update food by params
  patch "/:id/update", 
    to: "foods#update", 
    as: "foods_update"
  #delete food by params
  delete "/foods/:id", 
    to: "foods#destroy", 
    as: "foods_delete"

  #ORDERS MODEL
  get "/orders",
    to: "orders#index",
    as: "orders_index"

  delete "/orders/:id", 
    to: "orders#destroy", 
    as: "orders_delete"

  patch "orders/:id/update", 
    to: "orders#update", 
    as: "orders_update"
  

  #ORDERS DETAIL MODEL

  get "/orders/:order_id",
    to: "order_detail#index",
    as: "detail_index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: {maximum: 150}
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0.01 }

  has_many :categories, through: :menu_categories
  has_many :orders_detail
  has_many :orders, through: :order_detail

  
  def self.by_letter(letter)
    where("name LIKE ?", "#{letter}%").order(:name)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :foods, through: :order_details
  validates :email, format: { with: /[a-z0-9](\.?[a-z0-9]){5,}@g(oogle)?mail\.com/i,
message: "Your message" }

  def calculate_total(price, quantity)
    total += price * quantity
    update_total(total)
  end
  
  def update_total(total)
    self.update(total_price: total)
  end
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, inverse_of: :order_degailss
  belongs_to :product

  validates_presence_of :food
  validates_presence_of :order

  # def calculate_total
  #   total = 0.0
  #   total = self.food.price * self.quantity
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  protect_from_forgery
  def index
    @foods = Food.all
  end

  def home
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    @food = Food.find(params[:id])
    @food.update(foods_params)
    redirect_to foods_path
  end

  def foods_params
    params.require(:food).permit(:name, :category, :description, :price)
  end

  def new
    @food = Food.new
  end

  def create
    foods = Food.create(params.require(:food).permit(:name, :category, :description, :price))

    redirect_to foods_path
  end

  def destroy
    @get_id = Food.find(params[:id])
    
    @get_id.destroy
    redirect_to foods_index_path, notice: 'Task berhasil dihapus'
  end
end

app/controllers/order_detail_controller.rb
class OrderDetailController < ApplicationController
  def new
    @detail = OrderDetail.new
  end

  def create
    details = OrderDetail.create(params.require(:detail).permit(:orders_id, :item_id, :item_quantity, :price))

    redirect_to orders_path
  end

  def update
  end

  def destroy
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  protect_from_forgery
  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @detail = OrderDetail.new
    @foods = Food.all
  end

  def create
    # @order = Order.new(order_params)
    # @order.item_id = Food.find(params[:id])
    # @total = @order.calculate_total(@Food.price, :item_quantity)
    orders = Order.create(params.require(:order).permit(:email, :detail_id, :date, :status, :total_price))

    redirect_to orders_path
  end

  def get_total_price(id)
    @foods = Food.all
    
  end

  def edit
    @order = Order.find(params[:id])
    @foods = Food.all
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to orders_path
  end

  def order_params
    params.require(:order).permit(:email, :detail_id, :date, :status, :total_price)
  end

  def destroy
    @get_id = Order.find(params[:id])
    
    @get_id.destroy
    redirect_to orders_index_path, notice: 'Order berhasil dihapus'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/order_detail_helper.rb
module OrderDetailHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/foods/edit.html.erb
<body>
  <div class="sidebar">
    <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
    <a class="active" href="/"><h5>Home</h5></a>
    <a href="/orders">Orders</a>
    <a href="/about">About</a>
  </div>
  <div class="content-wrapper">
    <div class="content-container">
      <h2>EDIT <span><%= @food.name%></span></h2>
      <div class="form-edit">
        <%= form_with model: @food, url: foods_update_path do |f| %>
          <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Name</label>
          <%= f.text_field :name, placeholder: "name", :class => 'form-control' %>
          </div>
          <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Category</label>
          <%= f.text_field :category, placeholder: "category", :class => 'form-control' %>
          </div> 
          <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Description</label>
          <%= f.text_area :description, placeholder: "description",:class => 'form-control' %>
          </div>
          <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Price ( in Rupiah )</label>
          <%= f.text_field :price, placeholder: "price",:class => 'form-control' %>
          </div>
        <%= f.submit 'Update', :class => 'btn btn-danger'%>
        <% end %>
      </div>
    </div>
  </div>
</body>

          

app/views/foods/index.html.erb
<script>
  require("@rails/ujs").start()
  require("turbolinks").start()
  require("@rails/activestorage").start()
  require("channels")
</script>
<body>
  
  <div class="sidebar">
    <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
    <a class="active" href="/"><h5>Home</h5></a>
    <a href="/orders">Orders</a>
    <a href="/about">About</a>
    <button class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">Database</button>
  </div>
  <div class="content-wrapper">
    <div class="content-container">
      <h2>CATERING SERVICE.</h2>
      <div class="food-wrapper border-2">
        <% @foods.each do |food| %>
        <div class="parent">
          <div class="child" style="width: 18rem;">
            <% if food.category == "food"%>
              <img src="https://image-cdn.medkomtek.com/Dd70gq8gbttDcJLDEbkVD2wbvoo=/640x640/smart/klikdokter-media-buckets/medias/2321296/original/049998000_1605579809-Waspada_-Inilah-Deretan-Penyakit-Akibat-Junk-Food-shutterstock_537665956.jpg" class="card-img-top" alt="...">
            <% elsif food.category == "beverage"%>
              <img src="https://i.pinimg.com/originals/d6/fa/e8/d6fae83663966ccb64f8810df5c5634e.png" class="card-img-top" alt="...">
            <% end%>
            <div class="card-body">
              <div class="card-wrapper">
                <h4><%= food.name %></h4>
              </div>
            </div>
          </div>
          <div class="info-wrapper">
            <h5>Rp. <%= food.price %></h5>
            <a class="btn btn-danger" href="/foods/<%=food.id%>" role="button">Show</a>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

<!-- Modal -->

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Database</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <table class="table table-striped" style="width:100%;>
        <thead class="table-dark" style="background:#c12217;">
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Name</th>
            <th scope="col">Category</th>
            <th scope="col" style="width:50%;">Description</th>
            <th scope="col">Price</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td class="id" ><%= food.id %></td>
              <td class="name" ><%= food.name %></td>
              <td class="category" ><%= food.category %></td>
              <td class="description" ><%= food.description %></td>
              <td class="price" >Rp. <%= food.price %></td>
              <td class="button">
                <a class="btn btn-primary" href="/<%=food.id%>/edit" role="button">Edit</a>
                <%= button_to "Delete", foods_delete_path(food.id), :method => 'delete', :class => 'btn btn-danger'%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <a class="btn btn-success" href="foods/new" role="button">Add</a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/foods/new.html.erb
<body>
  <div class="sidebar">
    <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
    <a class="active" href="/"><h5>Home</h5></a>
    <a href="/orders">Orders</a>
    <a href="/about">About</a>
  </div>
  <div class="content-wrapper">
    <div class="content-container">
      <h2>CREATE <span>New Menu</span></h2>
      <div class="form-create">
        <%= form_with model: @food do |form| %>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Name</label>
          <%= form.text_field :name, placeholder: "name", :class => 'form-control' %>
        </div> 
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Category</label>
          <%= form.text_field :category, placeholder: "category" , :class => 'form-control' %>
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Description</label>
          <%= form.text_field :description, placeholder: "description" , :class => 'form-control' %>
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Price (in Rupiah)</label>
          <%= form.text_field :price, placeholder: "price" , :class => 'form-control' %>
        </div>
        <%= form.submit 'Create', :class => 'btn btn-danger'%>
      <% end %>
      </div>
    </div>
  </div>
</body>

app/views/foods/order.html.erb
<div class="sidebar">
    <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
    <a class="active" href="/"><h5>Home</h5></a>
    <a href="/orders">Orders</a>
    <a href="/about">About</a>
    <button class="btn btn-danger" data-toggle="modal" data-target="#exampleModal">
  Database
  </button>
  </div>

app/views/foods/show.html.erb
<body>
  <div class="sidebar">
    <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
    <a class="active" href="/"><h5>Home</h5></a>
    <a href="/orders">Orders</a>
    <a href="/about">About</a>
  </div>
  <div class="form">
    <h3><%= @food.name %></h3>
    <h4>Rp. <%= @food.price %></h4>
    <h5>Category : <span><%= @food.category %></span></h5>
    <p><%= @food.description %></p>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsRuby3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia">

    <%= stylesheet_link_tag "foods/show", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "foods/index", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "foods/new", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "foods/edit", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "orders/index", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "orders/new", "data-turbo-track": "reload" %>

      
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/order_detail/create.html.erb
<h1>OrderDetail#create</h1>
<p>Find me in app/views/order_detail/create.html.erb</p>

app/views/order_detail/destroy.html.erb
<h1>OrderDetail#destroy</h1>
<p>Find me in app/views/order_detail/destroy.html.erb</p>

app/views/order_detail/new.html.erb
<h1>OrderDetail#create</h1>
<p>Find me in app/views/order_detail/create.html.erb</p>

app/views/order_detail/show.html.erb
<h1>OrderDetail#show</h1>
<p>Find me in app/views/order_detail/show.html.erb</p>

app/views/order_detail/update.html.erb
<h1>OrderDetail#update</h1>
<p>Find me in app/views/order_detail/update.html.erb</p>

app/views/orders/edit.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<body>
  <div class="sidebar">
    <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
    <a class="active" href="/"><h5>Home</h5></a>
    <a href="/orders">Orders</a>
    <a href="/about">About</a>
  </div>
  <div class="content-wrapper">
    <div class="content-container">
      <h2>EDIT <span><%= @order.email %>'s Order</span></h2>
      <div class="form-create">
        <%= form_with model: @order do |form| %>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email</label>
          <%= form.text_field :email, placeholder: "email", :class => 'form-control' %>
        </div> 
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">ID Detail</label>
          <%= form.text_field :detail_id, placeholder: "detail_id" , :class => 'form-control' %>
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label" input type="date">Date (YYYY-MM-DD)</label>
          <%= form.text_field :date, placeholder: "date" , :class => 'form-control' %>
        </div>
        <div class="mb-3">



        <table class="table table-striped" style="width:100%;>
        <thead class="table-dark" style="background:#c12217;">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td class="name" ><%= food.name %></td>
              <td class="quantity">
                <%= form_with model: @detail do |f| %>
                <%= f.text_field :item_quantity, placeholder: "0" , :class => 'form-control' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
        <label for="form-select form-select-lg mb-3" class="form-label">Status</label>
        <div class="mb-3">
          <%= form.select(:status, options_for_select(['NEW','PAID', 'CANCELLED'])) %>
        </div>
        <%= form.submit 'Update', :class => 'btn btn-danger'%>
      <% end %>
      </div>
    </div>
  </div>

        
</body>
<script type="text/javascript">
    function addMore(){
    $("#dynamic-inputs").append($("#original-inputs").html())
  }

  function submiForm() {
    let data = []
    $("[name='label']").each((i, item)=>
    {
      data.push({'label': item.value, 'amount':  $("[name='amount']")[i].value})
    })
    console.log({'quote_amounts': data})
    $.ajax({
        url: 'urlOfYourActionController',
        data: {'quote_amounts': data},
        type: 'POST',
        success: function(data){
            // handle your success here
            console.log(data);
        }
    });
  }
</script>

app/views/orders/index.html.erb
<body>
    <div class="sidebar">
      <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
      <a class="active" href="/"><h5>Home</h5></a>
      <a href="/orders">Orders</a>
      <a href="/about">About</a>
  </div>
  <div class="orders-container">
    <div class="orders-body">
      <h2>ORDER <span>LIST</span></h2>
      <table class="table table-dark table-striped" style="width:100%;>
        <thead class="table-dark" style="background:#c12217;">
          <tr class="thead">
            <th scope="col">ID</th>
            <th scope="col">Email</th>
            <th scope="col">Detail_id</th>
            <th scope="col">Date</th>
            <th scope="col">Total Price</th>
            <th scope="col" style="width:10%;">Status</th>
            <th scope="col" style="width:20%;"></th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr class="tbody">
              <td class="id" ><%= order.id %></td>
              <td class="email" ><%= order.email %></td>
              <td class="detail_id" ><%= order.detail_id %></td>
              <td class="date" ><%= order.date %></td>
              <td class="total_price" >Rp. <%= order.total_price %></td>
              <td class="status" >
                <% if order.status == "NEW" %>
                    <b style="color:#fcec00;"><%= order.status %></b>
                <% elsif order.status == "PAID" %>
                    <b style="color:#00ff26;"><%= order.status %></b>
                <% elsif order.status == "CANCELLED" %>
                    <b style="color:#fc1100;"><%= order.status %></b>
                <% end %>
              </td>
              <td class="btn-wrapper">
                <a class="btn btn-success btn-sm" href="#orders/<%=order.id%>/detail" role="button" style="width:50px; text-align:center;">Detail</a>
                <a class="btn btn-primary btn-sm" href="orders/<%=order.id%>/edit" role="button" style="width:50px; text-align:center;">Edit</a>
                <%= button_to "Delete", orders_delete_path(order.id), :method => 'delete', :class => 'btn btn-danger btn-sm', style: "width:55px; text-align:center;"%>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <a class="btn btn-success btn-sm" href="/orders/new" role="button" style="text-align:center;">Create Order</a>
    </div>
  </div>
</body>

app/views/orders/new.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<body>
  <div class="sidebar">
    <img src="https://st2.depositphotos.com/1031343/5867/v/380/depositphotos_58676587-stock-illustration-catering-stamp.jpg?forcejpeg=true" class="img-logo" style="width:200px;">
    <a class="active" href="/"><h5>Home</h5></a>
    <a href="/orders">Orders</a>
    <a href="/about">About</a>
  </div>
  <div class="content-wrapper">
    <div class="content-container">
      <h2>CREATE <span>New Order</span></h2>
      <div class="form-create">
        <%= form_with model: @order do |form| %>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email</label>
          <%= form.text_field :email, placeholder: "email", :class => 'form-control' %>
        </div> 
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">ID Detail</label>
          <%= form.text_field :detail_id, placeholder: "detail_id" , :class => 'form-control' %>
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label" input type="date">Date (YYYY-MM-DD)</label>
          <%= form.text_field :date, placeholder: "date" , :class => 'form-control' %>
        </div>
        <div class="mb-3">



        <table class="table table-striped" style="width:100%;>
        <thead class="table-dark" style="background:#c12217;">
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Quantity</th>
          </tr>
        </thead>
        <tbody>
          <% @foods.each do |food| %>
            <tr>
              <td class="name" ><%= food.name %></td>
              <td class="quantity">
                <%= form_with model: @detail do |f| %>
                <%= f.text_field :item_quantity, placeholder: "0" , :class => 'form-control' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
        <label for="form-select form-select-lg mb-3" class="form-label">Status</label>
        <div class="mb-3">
          <%= form.select(:status, options_for_select(['NEW','PAID', 'CANCELLED'])) %>
        </div>
        <%= form.submit 'Create', :class => 'btn btn-danger'%>
      <% end %>
      </div>
    </div>
  </div>

        
</body>
<script type="text/javascript">
    function addMore(){
    $("#dynamic-inputs").append($("#original-inputs").html())
  }

  function submiForm() {
    let data = []
    $("[name='label']").each((i, item)=>
    {
      data.push({'label': item.value, 'amount':  $("[name='amount']")[i].value})
    })
    console.log({'quote_amounts': data})
    $.ajax({
        url: 'urlOfYourActionController',
        data: {'quote_amounts': data},
        type: 'POST',
        success: function(data){
            // handle your success here
            console.log(data);
        }
    });
  }
</script>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>